spring:
  application:
    name: telemetry-collector
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

mqtt:
  host: ${MQTT_HOST}
  port: ${MQTT_PORT}
  topic: ${MQTT_TOPIC}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}

kafka:
  topic:
    raw: ${KAFKA_TOPIC_RAW}
    dlq: ${KAFKA_TOPIC_DLQ}

logging:
  level:
    org.apache.kafka: OFF
